DECLARE @VEHICULE INT
DECLARE @BASE DECIMAL(8,2)
DECLARE @TPS DECIMAL(8,2)
DECLARE @TVQ DECIMAL(8,2)
DECLARE @TOTAL DECIMAL(8,2)

CREATE TABLE Acheteur
 (VEHICULE INT CONSTRAINT PK_Droits PRIMARY KEY, 
  BASE DECIMAL(8,2),
  TPS DECIMAL(8,2),
  TVQ DECIMAL(8,2),
  TOTAL DECIMAL(8,2))

DECLARE Tax_cursor CURSOR
FOR
	SELECT ID_vehicule, coutTransaction
	FROM VENDRE
OPEN Tax_cursor;
FETCH NEXT FROM Tax_cursor INTO @VEHICULE, @BASE

WHILE (@@FETCH_STATUS <> -1)
BEGIN
SET @TPS=STR(0.05*@BASE,8,2)
SET @TVQ=STR(0.09975*@BASE,8,2)
SET @TOTAL=STR(@TPS+@TVQ+@BASE,8,2)
 
INSERT INTO Acheteur
VALUES (@VEHICULE, @BASE, @TPS, @TVQ, @TOTAL)
FETCH NEXT FROM Tax_cursor INTO @VEHICULE, @BASE
END
CLOSE Tax_cursor
DEALLOCATE Tax_cursor

SELECT * FROM Acheteur
